default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV['DB_POOL'] || 5  %>
  database: <%= ENV['DB_NAME'] || 'registration_api_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'registration_api_development' %>
  username: root
  password: rootuser
  pool: 5
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: registration_api_test

  username: root
  password: rootuser
  pool: 5
  host: 127.0.0.1
  port: 3306

beta:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'freshtrak_private_beta' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'freshtrak_private' %>
